# Плагин LinksLobby - Lite! Плагин позволяет настраивать различные функции на сервере Лобби.
# Написал: vk.com/l1nkplay
#
# Это Lite версия плагина, которая распространяется бесплатно!

# Внимание! Автоматические функции плагина:
# [+] запрет: получения урона, голода, смена погоды, чата, команд, сообщения при входе/выходе/кике/смерти
# [+] выдача эффекта: прыгучести, скорости
# [+] Включение сообщения при входе(JoinMessage)


# НАСТРОЙКИ ФУНКЦИЙ ПЛАГИНА!
BlockActive: "&cВы не можете писать в чат!"
allow_cmd: #Команды которые можно писать при Commands: true
  - 'skins'
  - 'skin'
  - 'ms'
  - 'ds'
  - 'reg'
  - 'register'
  - 'l'
  - 'login'
  - 'cp'
  - 'changepassword'
  - 'menu'

JoinMessage:
  - '§b◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼ '
  - '§b◼ '
  - '§b◼  §6Ты в лобби проекта §b§lAsd§a§lMc!'
  - '§b◼ '
  - '§b◼  §cИнформация о проекте ниже §8>>>'
  - '§b◼  §fГруппа ВКонтакте§f: §avk.com/asdmcru '
  - '§b◼  §fПокупка доната на сайте§f: §bwww.AsdMc.space '
  - '§b◼  §fВыбор сервера§f: §e/menu  '
  - '§b◼  '
  - '§b◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼ '


# Версия плагина: 1.2